name: steamyanalytics
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  avg_counter:
    container_name: avg_counter
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: avg_counter:latest
    networks:
    - testing_net
  client:
    container_name: client
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_started
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./datasets:/datasets
    - ./results:/results
  english_1:
    container_name: english_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - INSTANCE_ID=1
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: english:latest
    networks:
    - testing_net
  english_2:
    container_name: english_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - INSTANCE_ID=2
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: english:latest
    networks:
    - testing_net
  english_3:
    container_name: english_3
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - INSTANCE_ID=3
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: english:latest
    networks:
    - testing_net
  english_4:
    container_name: english_4
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - INSTANCE_ID=4
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: english:latest
    networks:
    - testing_net
  english_5:
    container_name: english_5
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - INSTANCE_ID=5
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: english:latest
    networks:
    - testing_net
  genre_1:
    container_name: genre_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - INSTANCE_ID=1
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: genre:latest
    networks:
    - testing_net
  os_counter:
    container_name: os_counter
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: os_counter:latest
    networks:
    - testing_net
  q3_joiner:
    container_name: q3_joiner
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: q3_joiner:latest
    networks:
    - testing_net
  q4_joiner:
    container_name: q4_joiner
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: q4_joiner:latest
    networks:
    - testing_net
  q5_joiner:
    container_name: q5_joiner
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: q5_joiner:latest
    networks:
    - testing_net
  rabbitmq:
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 30s
      test:
      - CMD
      - rabbitmq-diagnostics
      - status
      timeout: 5s
    image: rabbitmq:3.13-management
    logging:
      driver: none
    networks:
    - testing_net
    ports:
    - 5672:5672
    - 15672:15672
  release_date_1:
    container_name: release_date_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - INSTANCE_ID=1
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: release_date:latest
    networks:
    - testing_net
  score_1:
    container_name: score_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - INSTANCE_ID=1
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: score:latest
    networks:
    - testing_net
  server:
    container_name: server
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
  trimmer_1:
    container_name: trimmer_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - INSTANCE_ID=1
    - TRIMMER_INSTANCES=1
    - GENRE_INSTANCES=1
    - SCORE_INSTANCES=1
    - RELEASE_DATE_INSTANCES=1
    - ENGLISH_INSTANCES=5
    image: trimmer:latest
    networks:
    - testing_net
