name: steamyanalytics
networks:
  testing_net:
    ipam:
      config:
        - subnet: 172.25.125.0/24
      driver: default
services:
  watchdog_1:
    container_name: watchdog_1
    # depends_on:
    #   propagator_1:
    #     condition: service_started
    #   rabbitmq:
    #     condition: service_healthy
    #   trimmer_1:
    #     condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INSTANCE_ID=1
      - TRIMMER_INSTANCES=0
      - GENRE_INSTANCES=0
      - SCORE_INSTANCES=0
      - RELEASE_DATE_INSTANCES=0
      - ENGLISH_INSTANCES=0
      - CLIENT_INSTANCES=0
      - OS_COUNTER_REPLICA_INSTANCES=0
      - AVG_COUNTER_REPLICA_INSTANCES=0
      - Q3_JOINER_REPLICA_INSTANCES=0
      - Q4_JOINER_REPLICA_INSTANCES=0
      - Q5_JOINER_REPLICA_INSTANCES=0
      - WATCHDOG_INSTANCES=3
      - PROPAGATOR_REPLICA_INSTANCES=0
      - Q3_JOINER_INSTANCES=0
      - Q4_JOINER_INSTANCES=0
      - Q5_JOINER_INSTANCES=0
      - OS_COUNTER_INSTANCES=0
      - AVG_COUNTER_INSTANCES=0
      - PROPAGATOR_INSTANCES=0
    image: watchdog:latest
    networks:
      - testing_net
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  watchdog_2:
    container_name: watchdog_2
    # depends_on:
    #   propagator_1:
    #     condition: service_started
    #   rabbitmq:
    #     condition: service_healthy
    #   trimmer_1:
    #     condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INSTANCE_ID=2
      - TRIMMER_INSTANCES=0
      - GENRE_INSTANCES=0
      - SCORE_INSTANCES=0
      - RELEASE_DATE_INSTANCES=0
      - ENGLISH_INSTANCES=0
      - CLIENT_INSTANCES=0
      - OS_COUNTER_REPLICA_INSTANCES=0
      - AVG_COUNTER_REPLICA_INSTANCES=0
      - Q3_JOINER_REPLICA_INSTANCES=0
      - Q4_JOINER_REPLICA_INSTANCES=0
      - Q5_JOINER_REPLICA_INSTANCES=0
      - WATCHDOG_INSTANCES=3
      - PROPAGATOR_REPLICA_INSTANCES=0
      - Q3_JOINER_INSTANCES=0
      - Q4_JOINER_INSTANCES=0
      - Q5_JOINER_INSTANCES=0
      - OS_COUNTER_INSTANCES=0
      - AVG_COUNTER_INSTANCES=0
      - PROPAGATOR_INSTANCES=0
    image: watchdog:latest
    networks:
      - testing_net
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  watchdog_3:
    container_name: watchdog_3
    # depends_on:
    #   propagator_1:
    #     condition: service_started
    #   rabbitmq:
    #     condition: service_healthy
    #   trimmer_1:
    #     condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INSTANCE_ID=3
      - TRIMMER_INSTANCES=0
      - GENRE_INSTANCES=0
      - SCORE_INSTANCES=0
      - RELEASE_DATE_INSTANCES=0
      - ENGLISH_INSTANCES=0
      - CLIENT_INSTANCES=0
      - OS_COUNTER_REPLICA_INSTANCES=0
      - AVG_COUNTER_REPLICA_INSTANCES=0
      - Q3_JOINER_REPLICA_INSTANCES=0
      - Q4_JOINER_REPLICA_INSTANCES=0
      - Q5_JOINER_REPLICA_INSTANCES=0
      - WATCHDOG_INSTANCES=3
      - PROPAGATOR_REPLICA_INSTANCES=0
      - Q3_JOINER_INSTANCES=0
      - Q4_JOINER_INSTANCES=0
      - Q5_JOINER_INSTANCES=0
      - OS_COUNTER_INSTANCES=0
      - AVG_COUNTER_INSTANCES=0
      - PROPAGATOR_INSTANCES=0
    image: watchdog:latest
    networks:
      - testing_net
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
