name: steamyanalytics
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - testing_net

  server:
    container_name: server
    image: server:latest
    volumes:
      - ./server/config.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  trimmer:
    container_name: trimmer
    image: trimmer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  genre:
    container_name: genre
    image: genre:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  score:
    container_name: score
    image: score:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  release_date:
    container_name: release_date
    image: release_date:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  english:
    container_name: english
    image: english:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  os_counter:
    container_name: os_counter
    image: os_counter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  avg_counter:
    container_name: avg_counter
    image: avg_counter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  q3_joiner:
    container_name: q3_joiner
    image: q3_joiner:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  q4_joiner:
    container_name: q4_joiner
    image: q4_joiner:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  q5_joiner:
    container_name: q5_joiner
    image: q5_joiner:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  client:
    container_name: client
    image: client:latest
    volumes:
      - ./datasets:/datasets
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_started

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
