name: steamyanalytics
services:
  server:
    container_name: server
    image: server:latest
    volumes:
      - ./server/config.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  trimmer:
    container_name: trimmer
    image: trimmer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  genre:
    container_name: genre
    image: genre:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  score:
    container_name: score
    image: score:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  release_date:
    container_name: release_date
    image: release_date:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  english:
    container_name: english
    image: english:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  os_counter:
    container_name: os_counter
    image: os_counter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  avg_counter:
    container_name: avg_counter
    image: avg_counter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  q3_joiner:
    container_name: q3_joiner
    image: q3_joiner:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  q4_joiner:
    container_name: q4_joiner
    image: q4_joiner:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  q5_joiner:
    container_name: q5_joiner
    image: q5_joiner:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  client:
    container_name: client
    image: client:latest # Asume que tienes una imagen para el cliente
    volumes:
      - ./datasets/reduced_games_corregido.csv:/datasets/games.csv
      - ./datasets/reduced_reviews.csv:/datasets/reviews.csv
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
